version: "3"
services:
  db:
   image: mysql:latest
   restart: always
   environment:
     - MYSQL_ROOT_PASSWORD:123456
     - MYSQL_DATABASE:develop
     - MYSQL_USER:develop
     - MYSQL_PASSWORD:123456
   volumes:
     - /data:/var/lib/mysql
  adminer:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    volumes:
     - ./conf/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
     - /phpmyadmin/phpmyadmin
