version: "3"
services:
  db:
   image: mysql:latest
   restart: always
   environment:
     - MYSQL_ROOT_PASSWORD:123456
     - MYSQL_DATABASE:develop
     - MYSQL_USER:develop
     - MYSQL_PASSWORD:123456
   volumes:
     - /data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
