version: "3"
services:
  mysql:
   image: mysql:latest
   restart: always
   environment:
     - MYSQL_ROOT_PASSWORD:123456
     - MYSQL_DATABASE:develop
     - MYSQL_USER:develop
     - MYSQL_PASSWORD:123456
   volumes:
     - /data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - TESTSUITE_PASSWORD=123456
    ports:
      - 8080:80
    depends_on:
      - mysql
