version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /data:/var/lib/mysql
      - ./conf/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.conf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    volumes:
      - /sessions
      - ./conf/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - 8080:80
    depends_on:
      - mysql
